/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.bosch

import spock.lang.Specification

class ExtendedBasePipelinerTest extends Specification {
    def "Test setupEnvironment method"() {
        given:
        def pipeliner = new ExtendedBasePipeliner() 

        when:
        pipeliner.setupEnvironment()

        then:
        // Write assertions here
        true
        
    }

    def "Test cleanUpEnvironment method"() {
        given:
        def pipeliner = new ExtendedBasePipeliner()

        when:
        pipeliner.cleanUpEnvironment()

        then:
        // Write assertions here
        true
    }
}